from emoji import emojize
input('>> Aperte ENTER para prosseguir após uma mensagem <<')
di = (emojize(':dorso_da_mão_com_indicador_apontando_para_a_direita_pele_morena_escura:', language= 'pt'))
es = (emojize(':dorso_da_mão_com_indicador_apontando_para_a_esquerda_pele_morena_escura:', language= 'pt'))
str(input('Você me ama? {}{} '.format(di, es)))
bj = (emojize(':rosto_mandando_um_beijo:', language= 'pt'))
input('Eu sabia que a reposta ja seria essa {}'.format(bj))
input('Eu sei la o que dizer agora')
input('Só')
input('Segura essa pedrada ai')
ap = (emojize(':indicador_apontando_para_o_visualizador_pele_morena_escura:', language= 'pt'))
input('que me faz lembrar MUITO de você {}'.format(ap))
ri = (emojize(':rosto_chorando_de_rir:', language= 'pt'))
input('Chora não miséria {}{}{}'.format(ri, ri, ri))
input('Aperte >> ENTER << para começar')
input('mais uma vez')
input('só mais uma')
input('a ultima')
input('{}'.format(9*ri))
input('agora é sério')
input('Aperta >> ENTER <<')
import pygame
pygame.init()
pygame.mixer_music.load('c:/users/ysouzz/Downloads/Portugal.mp3')
pygame.mixer_music.play()
input()
pygame.event.wait()
